### ISSUE TITLE
TypeError: Cannot read property 'V' of undefined

### ISSUE THREAD

**Issue by Ross1337** [wow0000/pronote-lib#1]
Salut, à peine téléchargé, tentative d'utiliser le get_homework(weekShift = 9) / get_timeplan(date = new Date()) . Je te poste le screen error :
![image](https://user-images.githubusercontent.com/45340378/76711247-86faae00-670e-11ea-9664-bb487625bcb5.png)
( ça fait la même depuis la lib originelle de litarvan, si tu sais patch... )

**Comment by wow0000** [comment]
Hey, je viens de sortir un patch sur github et npm, tu pourrais confirmer que il sois fonctionnel pour timeplan ?(Je n'ai pas encore corrigé homework tu peux quand même essayer)

**Comment by Ross1337** [comment]
J'update le tout et je te dit ça

**Comment by Ross1337** [comment]
J'ai uninstall - install pour être sûr, mais :
![image](https://user-images.githubusercontent.com/45340378/76711454-8c58f800-6710-11ea-9f31-f669bdf1139b.png)

**Comment by wow0000** [comment]
J'ai push un patch sur NPM pour corriger la salle si pronote ne la donne pas, ça devrais _normalement_ être le dernier soucis. Néanmoins ton emplois du temps retourné par l'api peut être vide donc vérifie bien le retour de l'api

**Comment by Ross1337** [comment]
![image](https://user-images.githubusercontent.com/45340378/76711550-739d1200-6711-11ea-8501-b24def9f1a41.png)
Je suppose que c'est ok, merci ;) D'ailleurs si tu veux la config d'un CAS très utilisé dans le sud, demande, il est pas donné dans les cas je l'ai fait maison, merci en tout cas les deux sont patch !
ps : n'hésite pas à faire un issue sur le git de litarvan pour patch car je suis pas le seul à avoir le prob

**Comment by wow0000** [comment]
Je suis pas contre le cas à vrai dire ^^ tu peux faire la PR le git de litarvan, je la mergerais.
Et oui je vais voir pour faire une PR sur le git de litarvan ^^

**Comment by Ross1337** [comment]
Je suis rouillé je galère à faire le PR j'ai fait un mini connerie, je t'envoi le CAS ici je te laisse faire la fatigue aide pas x)
CAS atrium-sud.fr

[atrium-sud.zip](https://github.com/wow0000/pronote-lib/files/4335268/atrium-sud.zip)
