### ISSUE TITLE
Erreur

### ISSUE THREAD

**Issue by ZKillou** [wow0000/pronote-lib#2]
![Screenshot_20200316-135900_Termux](https://user-images.githubusercontent.com/55600416/76762254-3bd5af00-6791-11ea-8eda-42ea2d851912.jpg)
Impossible de télécharger le package

**Comment by wow0000** [comment]
Bonjour, cette erreur ne vient pas de la librairie pronote-lib mais de "acorn" [https://github.com/acornjs/acorn](https://github.com/acornjs/acorn) Merci de rediriger votre erreur là bas.
