### ISSUE TITLE
Connexion à Pronote impossible

### ISSUE THREAD

**Issue by ZKillou** [wow0000/pronote-lib#3]
(node:1576) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)

(Je suis sur l'académie de Rennes)

**Comment by wow0000** [comment]
Bonjour, il me faudrait le code que tu as utilisé pour te connecter pour pouvoir t'aider
_Pense bien à retirer t'es identifiants si ils sont hard-codé_

**Comment by ZKillou** [comment]
let url = "https://0290033d.pronote.toutatice.fr/pronote/mobile.eleve.html";
let cas = "ac-rennes";

let user = new pronote.User({username: "id", "password": "password",url,cas}, function(){
    user.get_marks().then(function(res){
        console.log(res);
    }).catch(function(err){
        console.error(err);   
    })
})

**Comment by wow0000** [comment]
Ton url n'est pas valide,
```Javascript
let url = "https://0290033d.pronote.toutatice.fr/pronote/";
```
Il faut un / à la fin et retirer une page comme "mobile.eleve.html" qui pourrait être présente
Je te laisse me dire si tout fonctionne désormais

**Comment by ZKillou** [comment]
Ça n'a rien changé ...

**Comment by wow0000** [comment]
Je viens de vérifier et l'ac-renne n'est pas le bon nom à rentrer. La liste des académies des noms de fichiers ce trouve ici: [https://github.com/wow0000/pronote-lib/tree/master/src/cas](https://github.com/wow0000/pronote-lib/tree/master/src/cas)
Tu peux essayer avec cas="toutatice" néanmoins je ne suis pas sûr que cela fonctionnera. L'auteur original cette lib a noté rennes comme compatible néanmoins il n'est pas présent dans les fichiers, à partir de là je ne saurais pas trop t'aider et je t'invite a te rediriger vers l'auteur original pour avoir une réponse par rapport au support de ton CAS.

**Comment by ZKillou** [comment]
Toujours pas ...

**Comment by wow0000** [comment]
Je ferme l'issue car elle dépend du repo de Litarvan, comme dit dans le message au dessus je t'invite a le contacter pour connaitre les spécifications du CAS de ton établissement.
Pense également la prochaine fois à faire preuve de politesse.
