### ISSUE TITLE
Connection issue to ac-rennes = toutatice

### ISSUE THREAD

**Issue by madsenfr** [wow0000/pronote-lib#7]
Hello,
I want to create an Alexa skill (Amazon voicebot).
I cannot connect to pronote with any of theses cas : none, parent, toutatice.
I got "bad login".
I noticed a recent issue on pronote-api (https://github.com/Litarvan/pronote-api/issues/21), which I cannot use with Alexa environnement (build failed).
Do you plan to report the fix if it exists ?

**Comment by wow0000** [comment]
Hello !
Since the 2020 update of Pronote, this library is outdated and is kept for old version usage. I highly suggest you to use this instead
[https://github.com/Litarvan/pronote-api](https://github.com/Litarvan/pronote-api)
